from __future__ import annotations

from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "runtime"
if str(RUNTIME) not in sys.path:
    sys.path.insert(0, str(RUNTIME))

from claude_test_support import claude_packet, valid_claude_attestation  # noqa: E402
from core.provider_contract import RuntimeContract  # noqa: E402
from project_context import ProjectContext  # noqa: E402
from providers.claude.provider import ClaudeProvider  # noqa: E402


class ClaudeProviderTests(unittest.TestCase):
    def context(self): return ProjectContext(ROOT, ROOT, ROOT / "adapters" / "default")
    def provider(self): return ClaudeProvider()
    def packet(self): return claude_packet(self.provider().load_role_profile(self.context(), "context_scout"))

    def test_static_configuration_and_projection_are_real(self):
        provider=self.provider(); provider.validate_static_configuration(self.context())
        paths={item.relative_path.as_posix() for item in provider.projection_plan(self.context()).projections}
        self.assertIn("CLAUDE.local.md",paths); self.assertIn(".claude/hooks/governance-runtime-hook.py",paths); self.assertIn(".claude/agents/context-scout.md",paths)
        self.assertNotIn(".claude/settings.local.json",paths)
        profile=provider.load_role_profile(self.context(),"context_scout")
        self.assertTrue(profile.settings_projection_ref.endswith("/claude/governed-settings.json"))

    def test_context_scout_uses_native_selector_and_tool_restriction(self):
        provider=self.provider(); profile=provider.load_role_profile(self.context(),"context_scout")
        self.assertEqual((profile.runtime_role,profile.tier,profile.model,profile.model_resolution_mode),("context-scout","low","haiku","native"))
        self.assertEqual(provider.runtime_contract_for_role(profile),RuntimeContract("fresh","tool-restricted","disabled","runtime-observed"))

    def test_projected_agent_uses_only_child_scoped_hooks(self):
        projection=next(item for item in self.provider().projection_plan(self.context()).projections if item.relative_path.as_posix()==".claude/agents/context-scout.md")
        self.assertTrue(projection.content.startswith("---\n")); self.assertIn("tools: Read, Grep, Glob",projection.content); self.assertIn("mcpServers: []",projection.content)
        for token in ("PreToolUse:","PostToolUse:","PreCompact:","WorktreeCreate:"): self.assertIn(token,projection.content)
        for token in ("SubagentStart:","SubagentStop:","SessionStart:","SessionEnd:","InstructionsLoaded:"): self.assertNotIn(token,projection.content)
        marker=next(line for line in projection.content.splitlines() if "do not edit" in line); self.assertGreater(projection.content.index(marker),projection.content.index("\n---\n",4))

    def test_projected_hook_is_managed_and_nonce_scoped(self):
        projection=next(item for item in self.provider().projection_plan(self.context()).projections if item.relative_path.as_posix()==".claude/hooks/governance-runtime-hook.py")
        self.assertTrue(projection.content.startswith("# Generated by sitter; do not edit.\n"))
        for token in ("SITTER_CLAUDE_EVIDENCE_DIR","SITTER_CLAUDE_ATTEMPT_NONCE","SITTER_CLAUDE_EXECUTION_MODE","O_EXCL"): self.assertIn(token,projection.content)

    def test_complete_valid_attestation_is_accepted(self):
        packet=self.packet(); evidence=self.provider().validate_attestation(packet,valid_claude_attestation(packet)); self.assertEqual(evidence.provider,"claude")

    def test_attestation_mutations_are_rejected(self):
        packet=self.packet()
        for label,mutate,pattern in (
            ("tool",lambda a:a["observed"].update(tools_used=["Read","Bash"]),"tools_used"),
            ("continuity",lambda a:a["observed"].update(continuity_events=["compact"]),"continuity_events"),
            ("hash",lambda a:a["evidence"].update(hook_projection_sha256="f"*64),"hook_projection_sha256"),
        ):
            with self.subTest(label=label):
                att=valid_claude_attestation(packet); mutate(att)
                with self.assertRaisesRegex(ValueError,pattern): self.provider().validate_attestation(packet,att)

    def test_managed_native_evidence_confusion_is_rejected(self):
        packet=self.packet(); att=valid_claude_attestation(packet,method="claude-native-subagent"); att["execution"]["collector"]="claude-stream-hooks-transcript-v2"
        with self.assertRaisesRegex(ValueError,"collector"): self.provider().validate_attestation(packet,att)


if __name__=="__main__": unittest.main()
