from __future__ import annotations

import hashlib
import subprocess
import tempfile
from pathlib import Path
import unittest
from unittest import mock

import yaml

import install as installer


class TransactionalReplaceTests(unittest.TestCase):
    def create_project(self, directory: str) -> Path:
        project = Path(directory) / "project"
        project.mkdir()
        result = subprocess.run(
            ["git", "init", str(project)],
            text=True,
            encoding="utf-8",
            capture_output=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        return project

    def install_previous_release_fixture(self, project: Path) -> dict[Path, bytes]:
        """Create the installed shape produced by the previous Sitter installer."""
        mirror = project / ".harness" / installer.PACKAGE_NAME
        mirror.mkdir(parents=True)

        entrypoint = project / "AGENTS.md"
        entrypoint.write_text(
            "<!-- Generated by sitter; do not edit. -->\n"
            "# legacy v4.1 entrypoint\n",
            encoding="utf-8",
        )
        stale_agent = project / ".codex" / "agents" / "legacy-retired.toml"
        stale_agent.parent.mkdir(parents=True)
        stale_agent.write_text(
            "# Generated by sitter; do not edit.\n"
            'model = "gpt-5.6-luna"\n',
            encoding="utf-8",
        )
        old_skill = (
            project
            / ".agents"
            / "skills"
            / "legacy-retired"
            / "SKILL.md"
        )
        old_skill.parent.mkdir(parents=True)
        old_skill.write_text(
            "# Generated by sitter; do not edit.\n",
            encoding="utf-8",
        )

        projections = {
            "AGENTS.md": hashlib.sha256(entrypoint.read_bytes()).hexdigest(),
            r".codex\agents\legacy-retired.toml": hashlib.sha256(
                stale_agent.read_bytes()
            ).hexdigest(),
            ".agents/skills/change-governor-retired/SKILL.md": hashlib.sha256(
                old_skill.read_bytes()
            ).hexdigest(),
        }
        (mirror / "manifest-lock.yaml").write_text(
            yaml.safe_dump(
                {
                    "package": installer.PACKAGE_NAME,
                    "format_version": 1,
                    "version": "0.4.1-local",
                    "projections": projections,
                },
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        (mirror / "legacy-package-sentinel.txt").write_text(
            "old mirror\n",
            encoding="utf-8",
        )

        durable = {
            project / ".agent-work" / "task-001" / "task.yaml": b"task-state\n",
            project / "changes" / "active" / "change-001" / "proposal.md": b"change-state\n",
            project / "knowledge" / "local-note.md": b"knowledge-state\n",
            project
            / ".harness"
            / f"{installer.PACKAGE_NAME}.models.local.yaml": b"schema_version: 1\nproviders: {}\n",
        }
        for path, content in durable.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        return durable

    def test_previous_release_is_recognized_as_verified_codex_only_install(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.install_previous_release_fixture(project)

            self.assertEqual(installer.installed_provider_ids(project), ("codex",))

    def test_previous_release_to_dual_provider_is_transactional_replace(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            durable = self.install_previous_release_fixture(project)
            before = {path: path.read_bytes() for path in durable}

            installer.install(
                project,
                dry_run=False,
                enable_provider_ids=("claude",),
            )

            lock = yaml.safe_load(
                (
                    project
                    / ".harness"
                    / installer.PACKAGE_NAME
                    / "manifest-lock.yaml"
                ).read_text(encoding="utf-8")
            )
            self.assertEqual(lock["enabled_providers"], ["codex", "claude"])
            self.assertEqual(
                lock["installation_strategy"],
                "transactional-replace",
            )
            self.assertTrue((project / "AGENTS.md").is_file())
            self.assertTrue((project / "CLAUDE.local.md").is_file())
            # Stale managed projection deletion has dedicated installer coverage.
            # This cross-release fixture focuses on provider/mirror replacement
            # and durable project-state preservation.
            self.assertFalse(
                (
                    project
                    / ".harness"
                    / installer.PACKAGE_NAME
                    / "legacy-package-sentinel.txt"
                ).exists()
            )
            self.assertEqual(
                {path: path.read_bytes() for path in durable},
                before,
            )

    def test_unmanaged_modified_v41_projection_blocks_replace_before_writing(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            durable = self.install_previous_release_fixture(project)
            mirror = project / ".harness" / installer.PACKAGE_NAME
            mirror_before = (mirror / "manifest-lock.yaml").read_bytes()
            entrypoint = project / "AGENTS.md"
            # Remove the Harness marker as well as changing the bytes. A drifted
            # generated file that retains the marker is repairable; this case
            # deliberately removes every remaining ownership proof.
            entrypoint.write_text("user-owned override\n", encoding="utf-8")

            with self.assertRaisesRegex(
                ValueError,
                "projection was modified",
            ):
                installer.install(
                    project,
                    dry_run=False,
                    enable_provider_ids=("claude",),
                )

            self.assertEqual(
                (mirror / "manifest-lock.yaml").read_bytes(),
                mirror_before,
            )
            self.assertFalse((project / "CLAUDE.local.md").exists())
            for path, content in durable.items():
                self.assertEqual(path.read_bytes(), content)

    def test_post_swap_failure_restores_v41_installation_and_durable_state(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            durable = self.install_previous_release_fixture(project)
            tracked = [
                project / "AGENTS.md",
                project / ".codex" / "agents" / "legacy-retired.toml",
                project
                / ".agents"
                / "skills"
                / "legacy-retired"
                / "SKILL.md",
                project
                / ".harness"
                / installer.PACKAGE_NAME
                / "manifest-lock.yaml",
                *durable.keys(),
            ]
            before = {path: path.read_bytes() for path in tracked}

            with mock.patch.object(
                installer,
                "write_exclude",
                side_effect=ValueError("injected transactional replace failure"),
            ):
                with self.assertRaisesRegex(
                    ValueError,
                    "injected transactional replace failure",
                ):
                    installer.install(
                        project,
                        dry_run=False,
                        enable_provider_ids=("claude",),
                    )

            for path, content in before.items():
                self.assertTrue(path.is_file(), path)
                self.assertEqual(path.read_bytes(), content, path)
            self.assertFalse((project / "CLAUDE.local.md").exists())
            self.assertFalse(
                (
                    project
                    / ".harness"
                    / f".{installer.PACKAGE_NAME}.previous"
                ).exists()
            )


if __name__ == "__main__":
    unittest.main()
