from __future__ import annotations

import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
import unittest
from unittest import mock

import install as installer_module


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
INSTALLER = PACKAGE_ROOT / "install.py"


def run_installer(project: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(INSTALLER), "--project", str(project), *extra],
        cwd=PACKAGE_ROOT,
        text=True,
        encoding="utf-8",
        capture_output=True,
    )


class InstallTests(unittest.TestCase):
    def create_project(self, directory: str) -> Path:
        project = Path(directory) / "project"
        project.mkdir()
        result = subprocess.run(["git", "init", str(project)], text=True, capture_output=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        return project

    def create_repository_with_worktree(self, directory: str) -> tuple[Path, Path]:
        repository = Path(directory) / "repository"
        repository.mkdir()
        result = subprocess.run(["git", "init", str(repository)], text=True, capture_output=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        result = subprocess.run(
            [
                "git",
                "-C",
                str(repository),
                "-c",
                "user.name=Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "--allow-empty",
                "-m",
                "initial",
            ],
            text=True,
            capture_output=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        worktree = Path(directory) / "worktree"
        result = subprocess.run(
            ["git", "-C", str(repository), "worktree", "add", str(worktree), "-b", "test-worktree"],
            text=True,
            capture_output=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        return repository, worktree

    def test_dry_run_lists_projections_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)

            result = run_installer(project, "--dry-run")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("AGENTS.md", result.stdout)
            self.assertFalse((project / ".harness").exists())
            self.assertFalse((project / "AGENTS.md").exists())
            self.assertFalse((project / ".gitignore").exists())

    def test_install_writes_only_local_projections_and_excludes_them(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)

            result = run_installer(project)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((project / ".harness" / "sitter" / "manifest-lock.yaml").is_file())
            source_locator = project / ".harness" / "sitter" / "source.yaml"
            self.assertEqual(source_locator.read_text(encoding="utf-8"), f"source_root: {PACKAGE_ROOT.resolve()}\n")
            entrypoint = (project / "AGENTS.md").read_text(encoding="utf-8")
            self.assertTrue(entrypoint.startswith("<!-- Generated by sitter"))
            self.assertIn("source.yaml", entrypoint)
            self.assertIn("do not edit", entrypoint)
            self.assertTrue((project / ".codex" / "config.toml").is_file())
            self.assertTrue((project / ".agents" / "skills" / "change-governor" / "SKILL.md").is_file())
            exclude = (project / ".git" / "info" / "exclude").read_text(encoding="utf-8")
            self.assertIn("sitter managed projections", exclude)
            self.assertFalse((project / ".gitignore").exists())
            self.assertIn("--trust-project", result.stdout)

    def test_install_refuses_to_overwrite_an_unmanaged_entrypoint(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            (project / "AGENTS.md").write_text("user-owned\n", encoding="utf-8")

            result = run_installer(project)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("unmanaged", result.stderr.lower())
            self.assertEqual((project / "AGENTS.md").read_text(encoding="utf-8"), "user-owned\n")

    def test_adopt_existing_backs_up_an_unmanaged_entrypoint_before_replacing_it(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            (project / "AGENTS.md").write_text("previous local harness\n", encoding="utf-8")

            result = run_installer(project, "--adopt-existing")

            self.assertEqual(result.returncode, 0, result.stderr)
            backup = project / ".harness" / "sitter" / "legacy-backup" / "AGENTS.md"
            self.assertEqual(backup.read_text(encoding="utf-8"), "previous local harness\n")
            self.assertTrue((project / "AGENTS.md").read_text(encoding="utf-8").startswith("<!-- Generated by sitter"))

    def test_install_uses_the_actual_git_worktree_root(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            _, project = self.create_repository_with_worktree(directory)

            result = run_installer(project)

            self.assertEqual(result.returncode, 0, result.stderr)
            ignored = subprocess.run(
                ["git", "-C", str(project), "check-ignore", "-q", "--", "AGENTS.md"],
                text=True,
                capture_output=True,
            )
            self.assertEqual(ignored.returncode, 0, ignored.stderr)

    def test_trust_project_updates_user_config_and_preserves_existing_content(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            codex_home = Path(directory) / "codex-home"
            codex_home.mkdir()
            config = codex_home / "config.toml"
            config.write_text("[agents]\nenabled = true\n# keep this comment\n", encoding="utf-8")

            result = run_installer(
                project,
                "--trust-project",
                "--codex-home",
                str(codex_home),
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            text = config.read_text(encoding="utf-8")
            self.assertIn("# keep this comment", text)
            parsed = tomllib.loads(text)
            self.assertEqual(parsed["projects"][str(project.resolve())]["trust_level"], "trusted")
            self.assertEqual(len(list(codex_home.glob("config.toml.bak.*"))), 1)

            repeated = run_installer(
                project,
                "--update",
                "--trust-project",
                "--codex-home",
                str(codex_home),
            )
            self.assertEqual(repeated.returncode, 0, repeated.stderr)
            self.assertEqual(config.read_text(encoding="utf-8"), text)
            self.assertEqual(len(list(codex_home.glob("config.toml.bak.*"))), 1)

    def test_trust_project_uses_git_common_root_for_linked_worktree(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            repository, project = self.create_repository_with_worktree(directory)
            codex_home = Path(directory) / "codex-home"

            result = run_installer(
                project,
                "--trust-project",
                "--codex-home",
                str(codex_home),
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            parsed = tomllib.loads((codex_home / "config.toml").read_text(encoding="utf-8"))
            self.assertEqual(parsed["projects"][str(repository.resolve())]["trust_level"], "trusted")
            self.assertNotIn(str(project.resolve()), parsed["projects"])

    def test_trust_project_refuses_to_override_explicit_untrusted_without_force(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            codex_home = Path(directory) / "codex-home"
            codex_home.mkdir()
            config = codex_home / "config.toml"
            key = str(project.resolve()).replace("\\", "\\\\")
            config.write_text(
                f'[projects."{key}"]\ntrust_level = "untrusted"\n',
                encoding="utf-8",
            )

            refused = run_installer(
                project,
                "--trust-project",
                "--codex-home",
                str(codex_home),
            )

            self.assertNotEqual(refused.returncode, 0)
            self.assertIn("explicitly untrusted", refused.stderr)
            self.assertEqual(tomllib.loads(config.read_text(encoding="utf-8"))["projects"][str(project.resolve())]["trust_level"], "untrusted")

            approved = run_installer(
                project,
                "--force-trust-project",
                "--codex-home",
                str(codex_home),
            )
            self.assertEqual(approved.returncode, 0, approved.stderr)
            self.assertEqual(tomllib.loads(config.read_text(encoding="utf-8"))["projects"][str(project.resolve())]["trust_level"], "trusted")

    def test_trust_project_dry_run_does_not_modify_user_config(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            codex_home = Path(directory) / "codex-home"
            codex_home.mkdir()
            config = codex_home / "config.toml"
            original = "[agents]\nenabled = true\n"
            config.write_text(original, encoding="utf-8")

            result = run_installer(
                project,
                "--dry-run",
                "--trust-project",
                "--codex-home",
                str(codex_home),
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("would trust Codex project root", result.stdout)
            self.assertEqual(config.read_text(encoding="utf-8"), original)
            self.assertFalse(list(codex_home.glob("config.toml.bak.*")))

    def test_reinstall_replaces_the_mirror_and_removes_stale_managed_projections(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.assertEqual(run_installer(project).returncode, 0)

            mirror = project / ".harness" / "sitter"
            (mirror / "stale-package-file.txt").write_text("old package residue\n", encoding="utf-8")
            stale_agent = project / ".codex" / "agents" / "sitter-retired.toml"
            stale_agent.write_text("# Generated by sitter; do not edit.\n", encoding="utf-8")
            stale_skill = project / ".agents" / "skills" / "sitter-retired" / "SKILL.md"
            stale_skill.parent.mkdir(parents=True)
            stale_skill.write_text("# Generated by sitter; do not edit.\n", encoding="utf-8")
            work_file = project / ".agent-work" / "user-task" / "notes.md"
            work_file.parent.mkdir(parents=True)
            work_file.write_text("preserve this work artifact\n", encoding="utf-8")
            change_file = project / "changes" / "active" / "user-change" / "proposal.md"
            change_file.parent.mkdir(parents=True)
            change_file.write_text("preserve this change artifact\n", encoding="utf-8")

            result = run_installer(project, "--reinstall")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertFalse((mirror / "stale-package-file.txt").exists())
            self.assertFalse(stale_agent.exists())
            self.assertFalse(stale_skill.parent.exists())
            self.assertEqual(work_file.read_text(encoding="utf-8"), "preserve this work artifact\n")
            self.assertEqual(change_file.read_text(encoding="utf-8"), "preserve this change artifact\n")
            self.assertFalse((project / ".harness" / ".sitter.previous").exists())

    def test_reinstall_dry_run_preserves_stale_managed_projections(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.assertEqual(run_installer(project).returncode, 0)
            stale_agent = project / ".codex" / "agents" / "sitter-retired.toml"
            stale_agent.write_text("# Generated by sitter; do not edit.\n", encoding="utf-8")

            result = run_installer(project, "--dry-run", "--reinstall")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("would remove managed stale projection", result.stdout)
            self.assertTrue(stale_agent.exists())

    def test_reinstall_refuses_to_delete_an_unmanaged_stale_agent(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.assertEqual(run_installer(project).returncode, 0)
            stale_agent = project / ".codex" / "agents" / "sitter-user-custom.toml"
            stale_agent.write_text("user-owned configuration\n", encoding="utf-8")

            result = run_installer(project, "--reinstall")

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("unmanaged", result.stderr.lower())
            self.assertEqual(stale_agent.read_text(encoding="utf-8"), "user-owned configuration\n")

    def test_reinstall_refuses_to_delete_stale_skill_with_extra_content(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.assertEqual(run_installer(project).returncode, 0)
            stale_skill = project / ".agents" / "skills" / "sitter-retired"
            stale_skill.mkdir(parents=True)
            (stale_skill / "SKILL.md").write_text(
                "# Generated by sitter; do not edit.\n",
                encoding="utf-8",
            )
            extra = stale_skill / "user-notes.md"
            extra.write_text("preserve me\n", encoding="utf-8")

            result = run_installer(project, "--reinstall")

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("unmanaged stale skill content", result.stderr)
            self.assertEqual(extra.read_text(encoding="utf-8"), "preserve me\n")

    def test_reinstall_refuses_to_delete_unverified_mirror(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            mirror = project / ".harness" / "sitter"
            mirror.mkdir(parents=True)
            user_file = mirror / "user-owned.txt"
            user_file.write_text("do not delete\n", encoding="utf-8")

            result = run_installer(project, "--reinstall")

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("unverified Harness mirror", result.stderr)
            self.assertEqual(user_file.read_text(encoding="utf-8"), "do not delete\n")

    def test_reinstall_restores_previous_mirror_when_post_swap_step_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self.create_project(directory)
            self.assertEqual(run_installer(project).returncode, 0)
            mirror = project / ".harness" / "sitter"
            sentinel = mirror / "previous-version-sentinel.txt"
            sentinel.write_text("restore me\n", encoding="utf-8")
            codex_home = Path(directory) / "codex-home"

            with mock.patch.object(
                installer_module,
                "ensure_project_trusted",
                side_effect=ValueError("injected post-swap failure"),
            ):
                with self.assertRaisesRegex(ValueError, "injected post-swap failure"):
                    installer_module.install(
                        project,
                        dry_run=False,
                        reinstall=True,
                        trust_project=True,
                        codex_home=codex_home,
                    )

            self.assertEqual(sentinel.read_text(encoding="utf-8"), "restore me\n")
            self.assertFalse((project / ".harness" / ".sitter.previous").exists())


if __name__ == "__main__":
    unittest.main()
