from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path, PurePosixPath

import yaml

from project_context import ProjectContext, resolve_project_context
from review_transaction import atomic_write_yaml
from work_graph import now_iso, resolve_change_root


class TestHygieneError(ValueError):
    pass


def _status_paths(project: Path) -> set[str]:
    result = subprocess.run(
        ["git", "-C", str(project), "status", "--porcelain=v1", "-z", "--untracked-files=all"],
        text=True,
        encoding="utf-8",
        capture_output=True,
    )
    if result.returncode:
        raise TestHygieneError(result.stderr.strip() or "git status failed")
    records = result.stdout.split("\0")
    paths: set[str] = set()
    index = 0
    while index < len(records):
        record = records[index]
        index += 1
        if not record:
            continue
        if len(record) < 4:
            raise TestHygieneError(f"unexpected git status record: {record!r}")
        status = record[:2]
        path = record[3:].replace("\\", "/")
        if path:
            paths.add(path)
        if "R" in status or "C" in status:
            # -z porcelain emits the original path as the next NUL record.
            if index < len(records):
                index += 1
    return paths


def _looks_like_test(path: str) -> bool:
    normalized = path.replace("\\", "/").lower()
    parts = [part for part in normalized.split("/") if part]
    if any(part in {"test", "tests", "testing", "unittest", "unittests", "unit_tests"} for part in parts[:-1]):
        return True
    name = parts[-1] if parts else normalized
    stem = name.rsplit(".", 1)[0]
    return bool(
        stem.startswith("test_")
        or stem.startswith("test-")
        or stem.endswith("_test")
        or stem.endswith("-test")
        or stem.endswith("_tests")
        or stem.endswith("-tests")
        or re.search(r"(^|[_-])test([_-]|$)", stem)
    )


def _is_finalization_evidence(path: str) -> bool:
    """Exclude Harness-owned evidence that happens to contain ``test-``.

    ``test-finalization.yaml`` lives inside a Change and is generated by this
    transaction. Treating it as a changed business test makes the transaction
    fail on its own second run.
    """

    parts = PurePosixPath(path.replace("\\", "/")).parts
    return (
        len(parts) == 4
        and parts[0] == "changes"
        and parts[1] in {"active", "archive"}
        and parts[3] == "test-finalization.yaml"
    )


def _safe_relative(context: ProjectContext, value: str) -> str:
    """Validate a project-relative path without resolving Windows aliases.

    Git reports project-relative paths already. Using Path.resolve()/relative_to()
    here caused the same runner directory to appear once as a long path and once
    as an 8.3 short path on Windows. Syntactic validation is sufficient because
    the value is never used to escape the project root before this check.
    """

    normalized = value.replace("\\", "/").strip()
    if not normalized:
        raise TestHygieneError("test path must not be empty")
    if normalized.startswith(("/", "~")):
        raise TestHygieneError(f"test path must be project-relative: {value}")
    if len(normalized) >= 2 and normalized[1] == ":":
        raise TestHygieneError(f"test path must be project-relative: {value}")
    parts = PurePosixPath(normalized).parts
    if not parts or any(part in {"", ".", ".."} for part in parts):
        raise TestHygieneError(f"test path escapes project: {value}")
    # Keep the context argument in the contract: callers deliberately validate
    # paths against this project even though no filesystem canonicalization is
    # required here.
    if not context.project_root:
        raise TestHygieneError("project root is unavailable")
    return PurePosixPath(*parts).as_posix()


def _parse_classifications(context: ProjectContext, values: list[str], label: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for raw in values:
        if "=" not in raw:
            raise TestHygieneError(f"{label} must use PATH=REASON: {raw}")
        path_value, reason = raw.split("=", 1)
        path = _safe_relative(context, path_value)
        reason = reason.strip()
        if not reason:
            raise TestHygieneError(f"{label} reason must not be empty: {path}")
        if path in result:
            raise TestHygieneError(f"duplicate {label} path: {path}")
        result[path] = reason
    return result


def _load_change(change_root: Path) -> dict:
    data = yaml.safe_load((change_root / "change.yaml").read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TestHygieneError("change.yaml must be a mapping")
    return data


def _change_evidence_ref(change_root: Path) -> str:
    lifecycle_root = change_root.parent
    changes_root = lifecycle_root.parent
    if changes_root.name != "changes" or lifecycle_root.name not in {"active", "archive"}:
        raise TestHygieneError(
            "Change must remain under changes/active or changes/archive for test finalization"
        )
    return (
        Path("changes")
        / lifecycle_root.name
        / change_root.name
        / "test-finalization.yaml"
    ).as_posix()


def _existing_decisions(evidence: Path) -> list[dict[str, str]]:
    if not evidence.is_file():
        return []
    try:
        payload = yaml.safe_load(evidence.read_text(encoding="utf-8"))
    except yaml.YAMLError as error:
        raise TestHygieneError(f"invalid existing test finalization evidence: {evidence}") from error
    if not isinstance(payload, dict):
        raise TestHygieneError(f"existing test finalization evidence must be a mapping: {evidence}")
    raw = payload.get("decisions") or []
    if not isinstance(raw, list):
        raise TestHygieneError("existing test finalization decisions must be a list")
    decisions: list[dict[str, str]] = []
    for item in raw:
        if not isinstance(item, dict):
            raise TestHygieneError("existing test finalization decision must be a mapping")
        path = str(item.get("path") or "").strip()
        classification = str(item.get("classification") or "").strip()
        reason = str(item.get("reason") or "").strip()
        if not path or not classification or not reason:
            raise TestHygieneError("existing test finalization decision is incomplete")
        decisions.append(
            {"path": path, "classification": classification, "reason": reason}
        )
    return decisions


def _merge_decisions(
    previous: list[dict[str, str]],
    current: list[dict[str, str]],
) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    seen: set[tuple[str, str, str]] = set()
    for item in [*previous, *current]:
        key = (item["path"], item["classification"], item["reason"])
        if key in seen:
            continue
        seen.add(key)
        result.append(dict(item))
    return result


def finalize_tests(
    context: ProjectContext,
    change_root: Path,
    *,
    retained: dict[str, str],
    preexisting: dict[str, str],
) -> Path:
    data = _load_change(change_root)
    methodology = data.get("methodology") or {}
    protocol = methodology.get("test_cleanup_protocol")
    if protocol != 1:
        raise TestHygieneError(
            "this Change does not use test_cleanup_protocol 1; legacy cleanup must use its original contract"
        )

    temporary = {
        _safe_relative(context, str(value))
        for value in (methodology.get("temporary_tests") or [])
    }
    changed = _status_paths(context.project_root)
    changed_tests = {
        path
        for path in changed
        if _looks_like_test(path) and not _is_finalization_evidence(path)
    }
    allowed = {
        _safe_relative(context, str(value))
        for value in ((data.get("change_budget") or {}).get("allowed_test_changes") or [])
        if str(value).strip()
    }
    candidates = sorted(changed_tests | temporary | allowed | set(retained) | set(preexisting))

    overlap = set(retained) & set(preexisting)
    if overlap:
        raise TestHygieneError(
            "test path cannot be both retained and pre-existing: " + ", ".join(sorted(overlap))
        )

    decisions: list[dict[str, str]] = []
    unresolved: list[str] = []
    retained_entries: list[dict[str, str]] = []
    remaining_temporary: list[str] = []

    for path in candidates:
        absolute = context.project_root / Path(path)
        if path in preexisting:
            decisions.append({
                "path": path,
                "classification": "pre-existing-not-owned",
                "reason": preexisting[path],
            })
            continue
        if path in retained:
            decisions.append({
                "path": path,
                "classification": "permanent-regression",
                "reason": retained[path],
            })
            retained_entries.append({"path": path, "reason": retained[path]})
            continue
        if path in temporary and not absolute.exists():
            decisions.append({
                "path": path,
                "classification": "development-only-removed",
                "reason": "temporary test no longer exists after development",
            })
            continue
        if path in temporary:
            remaining_temporary.append(path)
            unresolved.append(
                f"temporary test remains: {path}; delete it or classify it with --retain PATH=REASON"
            )
            continue
        if path in changed_tests or path in allowed:
            unresolved.append(
                f"changed test is unclassified: {path}; use --retain PATH=REASON or --preexisting PATH=REASON"
            )

    if unresolved:
        raise TestHygieneError("; ".join(unresolved))

    evidence = change_root / "test-finalization.yaml"
    evidence_ref = _change_evidence_ref(change_root)
    evidence_data = {
        "schema_version": 1,
        "change_id": data.get("id") or change_root.name,
        "checked_at": now_iso(),
        "changed_test_paths": sorted(changed_tests),
        "decisions": _merge_decisions(_existing_decisions(evidence), decisions),
    }

    methodology["temporary_tests"] = remaining_temporary
    methodology["retained_test_rationale"] = retained_entries
    methodology["test_cleanup_complete"] = True
    methodology["test_cleanup_evidence"] = evidence_ref
    data["methodology"] = methodology

    original_change = (change_root / "change.yaml").read_bytes()
    original_evidence = evidence.read_bytes() if evidence.exists() else None
    try:
        atomic_write_yaml(evidence, evidence_data)
        atomic_write_yaml(change_root / "change.yaml", data)
    except BaseException:
        (change_root / "change.yaml").write_bytes(original_change)
        if original_evidence is None:
            evidence.unlink(missing_ok=True)
        else:
            evidence.write_bytes(original_evidence)
        raise
    return evidence


def main() -> None:
    parser = argparse.ArgumentParser(description="Finalize Change test hygiene")
    parser.add_argument("change")
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument(
        "--retain",
        action="append",
        default=[],
        metavar="PATH=REASON",
        help="retain a task-owned test as a durable regression test",
    )
    parser.add_argument(
        "--preexisting",
        action="append",
        default=[],
        metavar="PATH=REASON",
        help="mark an already-dirty user test path as outside this Change's cleanup ownership",
    )
    args = parser.parse_args()
    try:
        context = resolve_project_context(args.project)
        change_root = resolve_change_root(context, args.change)
        retained = _parse_classifications(context, args.retain, "--retain")
        preexisting = _parse_classifications(context, args.preexisting, "--preexisting")
        evidence = finalize_tests(
            context,
            change_root,
            retained=retained,
            preexisting=preexisting,
        )
        evidence_ref = _change_evidence_ref(change_root)
    except (ValueError, TestHygieneError) as error:
        raise SystemExit(str(error)) from error
    print(evidence_ref)


if __name__ == "__main__":
    main()
