from __future__ import annotations

import hashlib
from pathlib import Path

import yaml


MARKER = "Generated by sitter"
PACKAGE_NAME = "sitter"


def _lock_managed(path: Path) -> bool:
    """Recognize marker-free generated files through the installed lock.

    Some native configuration formats do not have a safe extension point for a
    generated-file comment. Those projections are managed only while their
    current bytes still match the hash and owner recorded by the Harness lock.
    Any user edit deliberately breaks ownership and prevents a silent overwrite.
    """

    resolved = path.resolve()
    for project_root in resolved.parents:
        lock = project_root / ".harness" / PACKAGE_NAME / "manifest-lock.yaml"
        if not lock.is_file():
            continue
        try:
            relative = resolved.relative_to(project_root).as_posix()
            data = yaml.safe_load(lock.read_text(encoding="utf-8"))
        except (ValueError, OSError, UnicodeError, yaml.YAMLError):
            return False
        if not isinstance(data, dict) or data.get("package") != PACKAGE_NAME:
            return False
        projections = data.get("projections")
        owners = data.get("projection_owners")
        if not isinstance(projections, dict) or not isinstance(owners, dict):
            return False
        expected = projections.get(relative)
        owner = owners.get(relative)
        if not isinstance(expected, str) or not isinstance(owner, str) or not owner:
            return False
        return hashlib.sha256(path.read_bytes()).hexdigest() == expected
    return False


def is_managed(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        header = path.read_text(encoding="utf-8").splitlines()[:20]
    except (OSError, UnicodeError):
        header = []
    if any(
        line
        in {
            f"<!-- {MARKER}; do not edit. -->",
            f"# {MARKER}; do not edit.",
        }
        for line in header
    ):
        return True
    return _lock_managed(path)


def assert_writable_projection(path: Path) -> None:
    if path.exists() and not is_managed(path):
        raise ValueError(f"refusing to overwrite unmanaged projection: {path}")


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()
